[package]
name = "tektra"
version = "0.1.0"
description = "AI Assistant with Avatar and Robotics Control - Native Rust implementation with Tauri frontend"
authors = ["David Irvine <david@davidjohnirvine.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/davidjohnirvine/tektra"
homepage = "https://github.com/davidjohnirvine/tektra"
documentation = "https://docs.rs/tektra"
readme = "README.md"
keywords = ["ai", "assistant", "chatbot", "robotics", "tauri"]
categories = ["gui", "multimedia", "science::robotics"]
include = [
    "src/**/*",
    "dist/**/*",
    "gen/**/*",
    "icons/**/*",
    "Cargo.toml",
    "build.rs",
    "tauri.conf.json",
    "README.md",
    "LICENSE-*"
]

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = "0.4"
dirs = "5.0"

# AI and ML (Native Rust - simplified approach)
tokenizers = "0.15"
hf-hub = { version = "0.3", features = ["tokio"] }
reqwest = { version = "0.11", features = ["json", "stream"] }
futures = "0.3"
candle-core = "0.8"
candle-nn = "0.8"
candle-transformers = "0.8"

# Vision (simplified for thread safety)
image = "0.25"

# Audio processing and I/O (simplified for compatibility)
# cpal = "0.15"
# rodio = "0.18" 
hound = "3.5"

# Networking
axum = "0.7"
tower = "0.5"

# Asset embedding for standalone binary
rust-embed = "8.0"
mime_guess = "2.0"

[features]
default = []

[[bin]]
name = "tektra"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true
