[package]
name = "tektra"
version = "0.1.0"
description = "AI Assistant with Avatar and Robotics Control"
authors = ["David Irvine"]
edition = "2021"

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = "0.4"
dirs = "5.0"

# AI and ML (Native Rust - simplified approach)
tokenizers = "0.15"
hf-hub = { version = "0.3", features = ["tokio"] }
reqwest = { version = "0.11", features = ["json", "stream"] }
futures = "0.3"
candle-core = "0.8"
candle-nn = "0.8"
candle-transformers = "0.8"

# Audio (simplified for initial build - will be enhanced later)
# cpal = "0.16"
# rodio = "0.19"

# Vision (simplified for thread safety)
# nokhwa = { version = "0.10", features = ["input-native"] }
image = "0.25"

# Networking
axum = "0.7"
tower = "0.5"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "tektra_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "tektra"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true
