[project]
name = "test-user-install"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "tektra==0.6.4",
]

[tool.uv.sources]
tektra = { workspace = true }
