apiVersion: apps/v1
kind: Deployment
metadata:
  name: tektra-app
  namespace: tektra
  labels:
    app.kubernetes.io/name: tektra
    app.kubernetes.io/component: application
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: tektra
      app.kubernetes.io/component: application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tektra
        app.kubernetes.io/component: application
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: tektra
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: tektra
        image: tektra:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: metrics
          containerPort: 8090
          protocol: TCP
        env:
        - name: TEKTRA_ENV
          value: "production"
        - name: TEKTRA_HOST
          value: "0.0.0.0"
        - name: TEKTRA_PORT
          value: "8000"
        - name: TEKTRA_DATABASE__URL
          valueFrom:
            secretKeyRef:
              name: tektra-secrets
              key: database-url
        - name: TEKTRA_REDIS__URL
          valueFrom:
            secretKeyRef:
              name: tektra-secrets
              key: redis-url
        - name: TEKTRA_SECURITY__JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: tektra-secrets
              key: jwt-secret
        - name: TEKTRA_SECURITY__SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tektra-secrets
              key: secret-key
        envFrom:
        - configMapRef:
            name: tektra-config
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: tektra-data
          mountPath: /app/data
        - name: tektra-logs
          mountPath: /app/logs
        - name: tektra-temp
          mountPath: /app/temp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: tektra-data
        persistentVolumeClaim:
          claimName: tektra-data
      - name: tektra-logs
        persistentVolumeClaim:
          claimName: tektra-logs
      - name: tektra-temp
        emptyDir:
          sizeLimit: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: tektra
                  app.kubernetes.io/component: application
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: tektra
            app.kubernetes.io/component: application