apiVersion: v1
kind: Service
metadata:
  name: tektra-service
  namespace: tektra
  labels:
    app.kubernetes.io/name: tektra
    app.kubernetes.io/component: application
    app.kubernetes.io/version: "1.0.0"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 8090
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: tektra
    app.kubernetes.io/component: application

---
apiVersion: v1
kind: Service
metadata:
  name: tektra-headless
  namespace: tektra
  labels:
    app.kubernetes.io/name: tektra
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: tektra
    app.kubernetes.io/component: application